# Generated by Django 2.2 on 2020-04-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Descricao', models.TextField(max_length=200)),
                ('Autor', models.CharField(max_length=50)),
                ('Data_lancamento', models.DateField()),
            ],
        ),
    ]
