# Generated by Django 2.2 on 2020-04-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='Data_lancamento',
        ),
    ]
